# Generated by Django 4.2.1 on 2023-05-19 14:00

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_picture', models.ImageField(blank=True, null=True, upload_to=Main.models.upload_image)),
                ('product_description', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('availability', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('product_category', models.ManyToManyField(blank=True, to='Main.category')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'db_table': 'Product',
            },
        ),
    ]
